### ISSUE TITLE
rtw_8822be driver problem: 101 errors during runtime

### ISSUE THREAD

**Issue by Newcool1230** [ZerBea/hcxdumptool#354] opened 2023-10-23 07:40 UTC
Running into `101 errors during runtime` error after <60sec of capturing handshakes, when trying to recapture again it will show the same error in <10 secs.

```
sudo hcxdumptool -i wlan0 -w dumpfile.pcapng
```

The first pcapng file looks fine and I can also `hcxpcapngtool` without issue (only warning), the second file it will throw `missing frames` errors.
```
Warning: out of sequence timestamps!
This dump file contains frames with out sequence timestamps.
That is a bug of the capturing tool.
```

OS, env, etc.:
```
$ lsb_release -a                          
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.3
Codename:       kali-rolling

$ uname -a
Linux Captain 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux

$ hcxdumptool --version
hcxdumptool 6.3.1 (C) 2023 ZeroBeat

$ hcxpcapngtool --version
hcxpcapngtool 6.2.7 (C) 2022 ZeroBeat

---------
$ sudo hcxdumptool -L                   

Requesting interface capabilities. This may take some time.
Please be patient...

available wlan devices:

phy idx hw-mac       virtual-mac  m ifname           driver (protocol)
---------------------------------------------------------------------------------------------
  0   2 7440bb49dc95 f04f7c3c9c96 + wlan0            rtw_8822be (NETLINK)

* active monitor mode available
+ monitor mode available
- no monitor mode available

bye-bye

------------
$ hcxdumptool -I wlan0   

Requesting interface capabilities. This may take some time.
Please be patient...

interface information:

phy idx hw-mac       virtual-mac  m ifname           driver (protocol)
---------------------------------------------------------------------------------------------
  0   2 7440bb49dc95 f04f7c3c9c96 + wlan0            rtw_8822be (NETLINK)


available frequencies: frequency [channel] tx-power of Regulatory Domain: 00

  2412 [  1] 20.0 dBm     2417 [  2] 20.0 dBm     2422 [  3] 20.0 dBm     2427 [  4] 20.0 dBm
  2432 [  5] 20.0 dBm     2437 [  6] 20.0 dBm     2442 [  7] 20.0 dBm     2447 [  8] 20.0 dBm
  2452 [  9] 20.0 dBm     2457 [ 10] 20.0 dBm     2462 [ 11] 20.0 dBm     2467 [ 12] 20.0 dBm
  2472 [ 13] 20.0 dBm     2484 [ 14] 20.0 dBm     5180 [ 36] 20.0 dBm     5200 [ 40] 20.0 dBm
  5220 [ 44] 20.0 dBm     5240 [ 48] 20.0 dBm     5260 [ 52] 20.0 dBm     5280 [ 56] 20.0 dBm
  5300 [ 60] 20.0 dBm     5320 [ 64] 20.0 dBm     5500 [100] 20.0 dBm     5520 [104] 20.0 dBm
  5540 [108] 20.0 dBm     5560 [112] 20.0 dBm     5580 [116] 20.0 dBm     5600 [120] 20.0 dBm
  5620 [124] 20.0 dBm     5640 [128] 20.0 dBm     5660 [132] 20.0 dBm     5680 [136] 20.0 dBm
  5700 [140] 20.0 dBm     5720 [144] 20.0 dBm     5745 [149] 20.0 dBm     5765 [153] 20.0 dBm
  5785 [157] 20.0 dBm     5805 [161] 20.0 dBm     5825 [165] 20.0 dBm

bye-bye
```

**Comment by ZerBea** [comment] 2023-10-23 08:22
Some information about the ERRORs and WARNINGs:

```
Warning: out of sequence timestamps!
This dump file contains frames with out sequence timestamps.
That is a bug of the capturing tool.
```
You're running an outdated version of hcxpcapngtool
```
$ hcxpcapngtool --version
hcxpcapngtool 6.2.7 (C) 2022 ZeroBeat
```
It can't handle the new time resolution of hcxdumptool > v6.3.0
It is mandatory to update to either v6.3.1 or latest git head.

`Running into 101 errors during runtime error after <60sec of capturing handshakes, when trying to recapture again it will show the same error in <10 secs.`

This is a driver problem. Packet injection is not working on this driver.

BTW:
Your report reminded me to add rtw_88xx chipsets/drivers (and in general all Realtek devices) to the list of not working (not working as expected) devices.

Please read more here (especially the Realtek section):
https://github.com/morrownr/USB-WiFi/issues/314

**Comment by ZerBea** [comment] 2023-10-23 08:46
A test on rtw_8821ce driver confirmed that packet injection is not working on this driver.
The R column of the status display remains empty.
```
$ uname -r
6.5.8-arch1-1

$ hcxdumptool -L

Requesting physical interface capabilities. This may take some time.
Please be patient...

available wlan devices:

phy idx hw-mac       virtual-mac  m ifname           driver (protocol)
---------------------------------------------------------------------------------------------
  0   3 70665594bd1f 70665594bd1f + wlp4s0           rtw_8821ce (NETLINK)

* active monitor mode available
+ monitor mode available
- no monitor mode available

bye-bye
```

There is nothing I can do. We have to wait for a driver fix.

**Comment by ZerBea** [comment] 2023-10-23 08:55
A frame injection test running aireplay-ng confirmed that the driver is not working as expected:
```
$ sudo ./aireplay-ng --test  wlp4s0
10:51:43  Trying broadcast probe requests...
10:51:45  No Answer...
10:51:45  Found 0 APs
```

I think we can close this report, because the problem is related to the driver (no frame injection).

**Closed by ZerBea** 2023-10-23 08:55 UTC

**Comment by ZerBea** [comment] 2023-10-23 09:21
BTW:
hcxdumptool has a similar function to test packet injection:
`$ sudo hcxdumptool -F --rcascan=active`

Terminate it after a period of a few minutes.
If you got a message like this frame injection is not working (driver bug):
`Warning: no responses received (packet injection may not work)`

**Comment by ZerBea** [comment] 2023-10-23 09:39
I reported this to bugzilla:
https://bugzilla.kernel.org/show_bug.cgi?id=218040

**Comment by ZerBea** [comment] 2023-10-26 11:56
Some good news:
https://bugzilla.kernel.org/show_bug.cgi?id=218040#c7

**Comment by ZerBea** [comment] 2023-10-26 12:28
Please notice:
Your kernel
```
$ uname -a
Linux Captain 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux
```
is outdated and not longer under maintenance:
https://www.kernel.org/

It will not get the fix.

**Comment by ZerBea** [comment] 2023-10-27 09:59
Looks like kernel 6.6 will be a good one regarding rtw88 driver. The compiled custom kernel (6.6-RC7) is running fine.
This custom kernel is very close to Arch Linux:
https://wiki.archlinux.org/title/Kernel

I do something between the traditional way
https://wiki.archlinux.org/title/Kernel/Traditional_compilation
and the Arch Build system
https://wiki.archlinux.org/title/Kernel/Arch_Build_System

**Comment by ZerBea** [comment] 2023-12-09 08:12
That is not a problem of hcxdumptool. It looks like the PCIe device has been deactivated by ASPM,
Please try this.
Add "rtw88_pci.disable_aspm=y" to the kernel command line on boot.
It will disable the Active-State Power Management of this device and hcxdumptool dosn't throw ERRORs any longer:

This is the status of my rtw_8821ce after ASPM has been disabled:
```
$ sudo hcxdumptool --rcascan=active

0 ERROR(s) during runtime
145 Packet(s) captured by kernel
0 Packet(s) dropped by kernel
42 PROBERESPONSE(s) captured

exit on sigterm
```

**Comment by ZerBea** [comment] 2023-12-09 09:55
BTW:
You shouldn't trust a test of short time duration.
This test maybe successful, but it doesn't detect if the device goes to sleep later on.
hcxdumptool detect this and it throws ERRORs.

Some words about KALI.
It is mandatory to configure/customize KALI. By default configuration It may not do what you expect.

**Comment by ZerBea** [comment] 2023-12-12 07:17
Please notice that there are still some open bugs:
https://bugzilla.kernel.org/show_bug.cgi?id=213195
https://bugzilla.kernel.org/show_bug.cgi?id=216386

Also please notice that it is in general not a good idea to use internal PCIe devices:
https://www.phoronix.com/news/AMD-WBRF-For-Linux-6.8

**Comment by LLH-l** [comment] 2024-02-19 09:59
kali-linux-2023.4  and wifislax64-3.4-final

Test using 8812bu (Chipset: rtw_8822be) cannot capture to PMKID
But can capture handshake

```
phy idx hw-mac       virtual-mac  m ifname           driver (protocol)
---------------------------------------------------------------------------------------------
  0   2 ffffffffffffff ffffffffffffff + wlan0            rtw_8822be (NETLINK)
```


```
 CHA   LAST   R 1 3 P S    MAC-AP    ESSID (last seen on top)     SCAN-FREQUENCY:   5745
-----------------------------------------------------------------------------------------
 149 17:36:34         + c43fffffffff CMCC-vKDZ



   LAST   E 2 MAC-AP-ROGUE   MAC-CLIENT   ESSID (last seen on top)
-----------------------------------------------------------------------------------------
^C
0 ERROR(s) during runtime
92 Packet(s) captured by kernel
0 Packet(s) dropped by kernel
1 SHB written to pcapng dumpfile
1 IDB written to pcapng dumpfile
1 ECB written to pcapng dumpfile
1 EPB written to pcapng dumpfile

exit on sigterm

```
seems no error

**Comment by ZerBea** [comment] 2024-02-19 16:44
8812bu is an out of tree kernel driver - it is not part of the Linux stock kernel:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/wireless/realtek?h=v6.7.5

There are several different drivers out in the wildness. Some of them may support packet injection and some not:
https://github.com/morrownr/88x2bu-20210702
https://github.com/fastoe/RTL8812BU

An overview is here:
https://github.com/morrownr/USB-WiFi/issues/314
