### ISSUE TITLE
hcxdumptool new style

### ISSUE THREAD

**Issue by anonymouse-257** [ZerBea/hcxdumptool#356] opened 2023-10-24 08:59 UTC
Hey I've read on other issue that hcxdumptool updated and removed all slow thing something like this,
And I'm watching some videos on YouTube (I've watched David Bombal tutorial) and he typed the following command:sudo hcxdumptool -i wlan0 -o dumpfile.pcapng --active_beacon --enable_status=1.
Now I've switched the -o in -w but the error is unrecognized option (that error appears to active beacon and enable status) and I know that hcxdumptool updated just idk what to do rn, how can I fix this

**Comment by ZerBea** [comment] 2023-10-24 10:37
You may have noticed that I have changed the head line  because there is already a discussion about that:
https://github.com/ZerBea/hcxdumptool/discussions/343

So we can close this report, because the new style is not a bug.

**Closed by ZerBea** 2023-10-24 10:37 UTC

**Comment by anonymouse-257** [comment] 2023-10-24 10:41
Aight tnx for the help and sorry for my bad English I'm more thing is how can I still use the enable staus option in the latest version what cmd do I need to type?

**Comment by ZerBea** [comment] 2023-10-24 10:46
`--enable_status has been replaced by --rds=1`

Typical commands are shown here:
https://github.com/ZerBea/hcxdumptool/issues/355#issuecomment-1776020019

**Comment by ZerBea** [comment] 2023-10-24 11:03
BTW:
My english is not much better.

**Comment by anonymouse-257** [comment] 2023-10-24 11:07
Aight thanks and you're English is very well I'm sure, now this is a fun question,what language this tool has written?

**Comment by ZerBea** [comment] 2023-10-24 11:07
I'm German.

**Comment by anonymouse-257** [comment] 2023-10-24 11:08
No,what is the code language that tool has written?

**Comment by ZerBea** [comment] 2023-10-24 11:09
Also I know that the entire 802.11 stuff is really hard to understand.
And everything is described in English which doesn't make things easier.

**Comment by ZerBea** [comment] 2023-10-24 11:09
Completely written in C.

**Comment by anonymouse-257** [comment] 2023-10-24 11:10
Wow, how old are you?

**Comment by anonymouse-257** [comment] 2023-10-24 11:11
btw how can I enable beacon in the latest version? Or the scan includes beacon in by default

**Comment by ZerBea** [comment] 2023-10-24 11:11
Close to 70 years

**Comment by anonymouse-257** [comment] 2023-10-24 11:12
fr?

**Comment by anonymouse-257** [comment] 2023-10-24 11:13
Man, I'm 16 😂

**Comment by ZerBea** [comment] 2023-10-24 11:13
Default options include transmitting a BEACON.
It can be disabled by --beacontx=0

**Comment by anonymouse-257** [comment] 2023-10-24 11:13
Aight tnx

**Comment by ZerBea** [comment] 2023-10-24 11:15
Either use the default value (10 BEACONs) or reduce it to 5 which will increase the chance that the target really find hcxdumptool during its scan.

**Comment by anonymouse-257** [comment] 2023-10-24 11:15
But wow completely on C man you're genius asf

**Comment by ZerBea** [comment] 2023-10-24 11:16
I have learned Assembler, but C is ok.

**Comment by anonymouse-257** [comment] 2023-10-24 11:16
Oh thanks

**Comment by anonymouse-257** [comment] 2023-10-24 11:18
Man, assembler? For real? You're Albert Einstein or something

**Comment by anonymouse-257** [comment] 2023-10-24 11:19
Oh and btw do you think that hashcat is faster on windows instead of VM?

**Comment by ZerBea** [comment] 2023-10-24 11:21
No, that was part of my of my education.

I don't use Windows and I don't use a VM. All my systems are running Linux. So I can't answer this questions.

**Comment by anonymouse-257** [comment] 2023-10-24 11:24
Oh you're runnin Linux as a default operating system btw what Linux Type you use?

**Comment by ZerBea** [comment] 2023-10-24 11:27
Desktop, notebook and netbook: Arch Linux
Raspberry Pi (Zero, A, B): Raspberry Pi OS Lite (Debian derivative)
Smart Phone: Lineage

**Comment by anonymouse-257** [comment] 2023-10-24 11:29
Wow man you are my inspiration
