### ISSUE TITLE
HCXDumpTool runtime error on MediaTEK MT7922 / MT7921E

### ISSUE THREAD

**Issue by jjbyrnes29** [ZerBea/hcxdumptool#393] opened 2024-01-04 09:56 UTC
![Screenshot_2024-01-04_03-49-06](https://github.com/ZerBea/hcxdumptool/assets/31814616/48e7c2e6-0cc8-4cde-8035-95f605dfbe22)

**Describe the bug**
HCXDumpTool runs, recognizes the wlan card, does not populate SSIDs, crashes with runtime errors and saves a pcapng file. 

**To Reproduce**
> sudo hcxdumptool 

**Expected behavior**
Lack of runtime errors causing crashing / population of SSIDs of access points. 

**Screenshots**
Output of **sudo hcxdumptool**:
![Screenshot_2024-01-04_03-47-14](https://github.com/ZerBea/hcxdumptool/assets/31814616/e6dd6f84-8fbe-44ab-a88e-9f6ff7cdf7d3)
![Screenshot_2024-01-04_03-47-43](https://github.com/ZerBea/hcxdumptool/assets/31814616/30e2a45f-dd28-4d92-81ce-4bc65eda7344)

Wireshark packet dump analysis of *.pcapng file:
![Screenshot_2024-01-04_03-48-15](https://github.com/ZerBea/hcxdumptool/assets/31814616/e104e00e-350a-444b-a54f-0f06d958fb9d)

Output of **inxi -Fxa** for wireless card. 
![Screenshot_2024-01-04_03-48-45](https://github.com/ZerBea/hcxdumptool/assets/31814616/1c79dbc0-ff26-4cc5-839d-0454ffcd8471)

Test of Packet Injection:
![Screenshot_2024-01-04_03-52-25](https://github.com/ZerBea/hcxdumptool/assets/31814616/2bcccad4-b895-44ba-b5ae-8fa2e937fad5)
![Screenshot_2024-01-04_03-45-13](https://github.com/ZerBea/hcxdumptool/assets/31814616/64fd0c1a-1f59-483b-8e98-5358f76635a3)

EDIT: I would like to add manually killing NetworkManager does not seemingly cause the crash issues, however there is no change in lack of access point population

**Comment by hyekalhitech** [comment] 2024-01-04 10:00
what kind of network adapter is this?

**Comment by jjbyrnes29** [comment] 2024-01-04 10:07
It's the internal NIC of my laptop

**Comment by jjbyrnes29** [comment] 2024-01-04 10:08
It's the internal NIC of my laptop.
I accidentally fat fingered that close with comment button.

**Comment by hyekalhitech** [comment] 2024-01-04 10:11
> It's the internal NIC of my laptop. I accidentally fat fingered that close with comment button.

try with the external network adapter. Seems like something is wrong with your MTK network adapter driver that can possibly make the devices not fully utilize by hcxdumptool.

**Comment by ZerBea** [comment] 2024-01-04 10:11
The driver is broken. Active monitor mode capability is reported by the driver, but not supported as expected.
There are several bug reports around this problem, e.g:
https://github.com/openwrt/mt76/issues/839

There is a workaround on hcxdumptool since 08.12.2023 and hcxdumptool does not trust this report any longer.
Active monitor mode must now be confirmed by -A option.
```
08.12.2023
==========
Some drivers report incorrectly active monitor mode capability.
hcxdumptool: do not set active monitor mode by default if driver report that it is possible
             removed option -p
             added new option -A in case active monitor mode is working as expected
             -A             : ACK incoming frames
                               INTERFACE must support active monitor mode
```

**Comment by ZerBea** [comment] 2024-01-04 10:13
Please udate to latest git head and run hcxdumptool without -A option, even it the driver report that active monitor mode is possible. That is definitely not the case.

**Comment by ZerBea** [comment] 2024-01-04 10:17
BTW:
airodump-ng and aireplay-ng are working, because the do not use active monitor mode.

**Comment by ZerBea** [comment] 2024-01-04 10:26
Your second scrrenshot is a nice example why hcxdumptool uses either frequency input (2412)  or channel input with additional band information (13a).
Since WiFi6 channel numbers are not longer unique:
1 = 2412
1 = 5955

**Comment by ZerBea** [comment] 2024-01-04 10:28
If you set active monitor mode by iw, aireplay-ng should crash the driver, too.

**Comment by jjbyrnes29** [comment] 2024-01-04 10:33
Running build: hcxdumptool 6.3.2-157-gc228432

Manually setting monitor mode via
> iw dev wlan0 set type monitor
> iw dev wlan0 set monitor active
Or
> iwconfig wlan0 mode monitor
Causes no changes towards hcxdumptool.

**Comment by ZerBea** [comment] 2024-01-04 10:35
That will always crach the driver:
"iw dev wlan0 set monitor active"

**Comment by ZerBea** [comment] 2024-01-04 10:37
Once it has been crashed, you must reload the driver or restart the system.
Than run hcxdumptool without -A option.
Do not use airmon-ng or iw.

**Comment by jjbyrnes29** [comment] 2024-01-04 10:38
Suprisingly enough, after reloading the driver and manually setting it via
> iw def wlan0 set type monitor

And not appending -A, program works flawlessly and I'm seeing output.

**Comment by ZerBea** [comment] 2024-01-04 10:40
There is no need to set monitor mode by iw, because hcxdumptool will do that via NETLINK messages.

**Comment by ZerBea** [comment] 2024-01-04 10:41
It looks like active monitor mode is broken on the entire mt79xx driver series.

**Comment by jjbyrnes29** [comment] 2024-01-04 10:43
Well, I can also confirm no need for the iw command now. Thanks a ton.

**Comment by ZerBea** [comment] 2024-01-04 10:45
Glad to hear this. Unfortunately, we can't use -A feature on this driver until it received a fix.
Closed as solved.

**Comment by jjbyrnes29** [comment] 2024-01-04 10:46
Wait a second, letting it run for a while causes runtime errors even though I'm seeing APs

**Closed by ZerBea** 2024-01-04 10:45 UTC

**Comment by ZerBea** [comment] 2024-01-04 11:02
This runtime errors are caused by the driver and hcxdumptool's internal ERROR COUNTER will increase.
That also happens if another process tries to get access to the INTERFACE while hcxdumptool is running.

**Comment by ZerBea** [comment] 2024-01-04 11:07
I guess you're running a notebook. In that case make sure that the OS does not enable power save while hcxdumptool is running.

**Comment by ZerBea** [comment] 2024-01-04 11:17
hcxdumptool treis to set power save off:
https://github.com/ZerBea/hcxdumptool/blob/master/hcxdumptool.c#L3373
It looks like this is ignored by the driver or overwritten by KALI.

**Comment by ZerBea** [comment] 2024-01-04 12:19
By latest commit, I have improved the status. If the internal ERROR count is > 0 this additional information is shown:
```
xx ERROR(s) during runtime
Possible reasons:
 driver is broken
 driver is busy (misconfigured system, other services access the INTERFACE)
```
