### ISSUE TITLE
Is the problem in the driver or in the operating system?

### ISSUE THREAD

**Issue by paolosezart** [ZerBea/hcxdumptool#408] opened 2024-01-24 09:06 UTC
I have a Raspberri pi 4 with Raspbian Bookworm operating system:
<details>
<summary>OS relase</summary>

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```
</details>

Next I will try to provide all the technical information about my hardware and operating system
<details>
<summary>ethtool</summary>

```
driver: rt2800usb
version: 6.1.0-rpi7-rpi-v8
firmware-version: 0.36
expansion-rom-version: 
bus-info: 1-1.3:1.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no


```
</details>

<details>
<summary>lshw</summary>

```
  *-usb:1
       description: Wireless interface
       product: RT2870 Wireless Adapter
       vendor: Ralink Technology, Corp.
       physical id: 3
       bus info: usb@1:1.3
       logical name: wlan1
       version: 0.01
       serial: f0:3f:03:d3:30:75:00:00:00:00:00:00:00:00
       capabilities: usb-2.00 logical wireless
       configuration: broadcast=yes driver=rt2800usb driverversion=6.1.0-rpi7-rpi-v8 firmware=0.36 link=yes maxpower=160mA multicast=yes speed=480Mbit/s wireless=IEEE 802.11
  *-interface:0
       description: Wireless interface
       product: 43430
       vendor: Broadcom
       physical id: 1
       bus info: mmc@1:0001:1
       logical name: mmc1:0001:1
       logical name: wlan0
       serial: 8c:84:01:02:01:03
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=brcmfmac driverversion=7.45.241 firmware=01-703fd60 ip=192.168.100.62 multicast=yes wireless=IEEE 802.11
  *-network
       description: Ethernet interface
       physical id: 9
       logical name: eth0
       serial: dc:a6:32:5a:d5:62
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=bcmgenet driverversion=6.1.0-rpi7-rpi-v8 link=no multicast=yes port=twisted pair


```
</details>

<details>
<summary>iwconfig wlan1</summary>

```
wlan1     IEEE 802.11  Mode:Monitor  Frequency:2.412 GHz  Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
```
</details>

<details>
<summary>iw list</summary>

```
Wiphy phy2
	wiphy index: 2
	max # scan SSIDs: 4
	max scan IEs length: 2257 bytes
	max # sched scan SSIDs: 0
	max # match sets: 0
	Retry short long limit: 2
	Coverage class: 0 (up to 0m)
	Device supports RSN-IBSS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP-128 (00-0f-ac:4)
		* CCMP-256 (00-0f-ac:10)
		* GCMP-128 (00-0f-ac:8)
		* GCMP-256 (00-0f-ac:9)
		* CMAC (00-0f-ac:6)
		* CMAC-256 (00-0f-ac:13)
		* GMAC-128 (00-0f-ac:11)
		* GMAC-256 (00-0f-ac:12)
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * mesh point
	Band 1:
		Capabilities: 0x27e
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			RX STBC 2-streams
			Max AMSDU length: 3839 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 2 usec (0x04)
		HT RX MCS rate indexes supported: 0-15, 32
		TX unequal modulation not supported
		HT TX Max spatial streams: 1
		HT TX MCS rate indexes supported may differ
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps (short preamble supported)
			* 5.5 Mbps (short preamble supported)
			* 11.0 Mbps (short preamble supported)
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (disabled)
	Band 2:
		Capabilities: 0x27e
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			RX STBC 2-streams
			Max AMSDU length: 3839 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 2 usec (0x04)
		HT RX MCS rate indexes supported: 0-15, 32
		TX unequal modulation not supported
		HT TX Max spatial streams: 1
		HT TX MCS rate indexes supported may differ
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5180 MHz [36] (disabled)
			* 5190 MHz [38] (disabled)
			* 5200 MHz [40] (disabled)
			* 5210 MHz [42] (disabled)
			* 5220 MHz [44] (disabled)
			* 5230 MHz [46] (disabled)
			* 5240 MHz [48] (disabled)
			* 5250 MHz [50] (disabled)
			* 5260 MHz [52] (30.0 dBm) (radar detection)
			* 5270 MHz [54] (30.0 dBm) (radar detection)
			* 5280 MHz [56] (30.0 dBm) (radar detection)
			* 5290 MHz [58] (30.0 dBm) (radar detection)
			* 5300 MHz [60] (30.0 dBm) (radar detection)
			* 5310 MHz [62] (30.0 dBm) (radar detection)
			* 5320 MHz [64] (30.0 dBm) (radar detection)
			* 5500 MHz [100] (disabled)
			* 5510 MHz [102] (disabled)
			* 5520 MHz [104] (disabled)
			* 5530 MHz [106] (disabled)
			* 5540 MHz [108] (disabled)
			* 5550 MHz [110] (disabled)
			* 5560 MHz [112] (disabled)
			* 5570 MHz [114] (disabled)
			* 5580 MHz [116] (disabled)
			* 5590 MHz [118] (disabled)
			* 5600 MHz [120] (disabled)
			* 5610 MHz [122] (disabled)
			* 5620 MHz [124] (disabled)
			* 5630 MHz [126] (disabled)
			* 5640 MHz [128] (disabled)
			* 5650 MHz [130] (disabled)
			* 5660 MHz [132] (disabled)
			* 5670 MHz [134] (disabled)
			* 5680 MHz [136] (disabled)
			* 5690 MHz [138] (disabled)
			* 5700 MHz [140] (disabled)
			* 5745 MHz [149] (30.0 dBm)
			* 5755 MHz [151] (30.0 dBm)
			* 5765 MHz [153] (30.0 dBm)
			* 5775 MHz [155] (30.0 dBm)
			* 5785 MHz [157] (30.0 dBm)
			* 5795 MHz [159] (30.0 dBm)
			* 5805 MHz [161] (30.0 dBm)
			* 5825 MHz [165] (30.0 dBm)
			* 4920 MHz [184] (disabled)
			* 4940 MHz [188] (disabled)
			* 4960 MHz [192] (disabled)
			* 4980 MHz [196] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * remain_on_channel
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * connect
		 * disconnect
		 * set_qos_map
		 * set_multicast_to_unicast
	software interface modes (can always be added):
		 * AP/VLAN
		 * monitor
	valid interface combinations:
		 * #{ AP, mesh point } <= 8,
		   total <= 8, #channels <= 1
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports low priority scan.
	Device supports scan flush.
	Device supports AP scan.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
	Device supports configuring vdev MAC-addr on create.
	max # scan plans: 1
	max scan plan interval: -1
	max scan plan iterations: 0
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xb0 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	Supported extended features:
		* [ RRM ]: RRM
		* [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
		* [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
		* [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
		* [ SCAN_RANDOM_SN ]: use random sequence numbers in scans
		* [ SCAN_MIN_PREQ_CONTENT ]: use probe request with only rate IEs in scans
		* [ CONTROL_PORT_NO_PREAUTH ]: disable pre-auth over nl80211 control port support
		* [ DEL_IBSS_STA ]: deletion of IBSS station support
		* [ SCAN_FREQ_KHZ ]: scan on kHz frequency support
		* [ CONTROL_PORT_OVER_NL80211_TX_STATUS ]: tx status for nl80211 control port support




Wiphy phy0
	wiphy index: 0
	max # scan SSIDs: 10
	max scan IEs length: 2048 bytes
	max # sched scan SSIDs: 16
	max # match sets: 16
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports roaming.
	Device supports T-DLS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP-128 (00-0f-ac:4)
		* CMAC (00-0f-ac:6)
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * P2P-client
		 * P2P-GO
		 * P2P-device
	Band 1:
		Capabilities: 0x1062
			HT20/HT40
			Static SM Power Save
			RX HT20 SGI
			RX HT40 SGI
			No RX STBC
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 16 usec (0x07)
		HT TX/RX MCS rate indexes supported: 0-7
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps (short preamble supported)
			* 5.5 Mbps (short preamble supported)
			* 11.0 Mbps (short preamble supported)
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (disabled)
	Band 2:
		Capabilities: 0x1062
			HT20/HT40
			Static SM Power Save
			RX HT20 SGI
			RX HT40 SGI
			No RX STBC
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 16 usec (0x07)
		HT TX/RX MCS rate indexes supported: 0-7
		VHT Capabilities (0x00001020):
			Max MPDU length: 3895
			Supported Channel Width: neither 160 nor 80+80
			short GI (80 MHz)
			SU Beamformee
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: not supported
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: not supported
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		VHT extended NSS: not supported
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5170 MHz [34] (disabled)
			* 5180 MHz [36] (disabled)
			* 5190 MHz [38] (disabled)
			* 5200 MHz [40] (disabled)
			* 5210 MHz [42] (disabled)
			* 5220 MHz [44] (disabled)
			* 5230 MHz [46] (disabled)
			* 5240 MHz [48] (disabled)
			* 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
			* 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
			* 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
			* 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
			* 5500 MHz [100] (disabled)
			* 5520 MHz [104] (disabled)
			* 5540 MHz [108] (disabled)
			* 5560 MHz [112] (disabled)
			* 5580 MHz [116] (disabled)
			* 5600 MHz [120] (disabled)
			* 5620 MHz [124] (disabled)
			* 5640 MHz [128] (disabled)
			* 5660 MHz [132] (disabled)
			* 5680 MHz [136] (disabled)
			* 5700 MHz [140] (disabled)
			* 5720 MHz [144] (disabled)
			* 5745 MHz [149] (20.0 dBm)
			* 5765 MHz [153] (20.0 dBm)
			* 5785 MHz [157] (20.0 dBm)
			* 5805 MHz [161] (20.0 dBm)
			* 5825 MHz [165] (20.0 dBm)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * join_ibss
		 * set_pmksa
		 * del_pmksa
		 * flush_pmksa
		 * remain_on_channel
		 * frame
		 * set_wiphy_netns
		 * set_channel
		 * tdls_oper
		 * start_sched_scan
		 * start_p2p_device
		 * connect
		 * disconnect
		 * crit_protocol_start
		 * crit_protocol_stop
		 * update_connect_params
	software interface modes (can always be added):
	valid interface combinations:
		 * #{ managed } <= 1, #{ P2P-device } <= 1, #{ P2P-client, P2P-GO } <= 1,
		   total <= 3, #channels <= 2
		 * #{ managed } <= 1, #{ AP } <= 1, #{ P2P-client } <= 1, #{ P2P-device } <= 1,
		   total <= 4, #channels <= 1
	Device supports scan flush.
	Device supports randomizing MAC-addr in sched scans.
	max # scan plans: 1
	max scan plan interval: 508
	max scan plan iterations: 0
	Supported TX frame types:
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	Supported extended features:
		* [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
		* [ 4WAY_HANDSHAKE_STA_PSK ]: 4-way handshake with PSK in station mode
		* [ 4WAY_HANDSHAKE_STA_1X ]: 4-way handshake with 802.1X in station mode
		* [ DFS_OFFLOAD ]: DFS offload
		* [ 4WAY_HANDSHAKE_AP_PSK ]: AP mode PSK offload support

```
</details>

<details>
<summary>sudo hcxdumptool check driver</summary>

```
initialization of hcxdumptool 6.2.6 (depending on the capabilities of the device, this may take some time)...
starting driver test...
driver tests passed...
all required ioctl() system calls are supported by driver

terminating...[?25h

```
</details>

<details>
<summary>sudo hcxdumptool -i wlan1 --check_injection</summary>

```
initialization of hcxdumptool 6.2.6 (depending on the capabilities of the device, this may take some time)...
starting antenna test and packet injection test (that can take up to two minutes)...
[?25lstage 1 of 2 probing frequency 2412/1 proberesponse 0
stage 1 of 2 probing frequency 2417/2 proberesponse 0   
stage 1 of 2 probing frequency 2422/3 proberesponse 0   
stage 1 of 2 probing frequency 2427/4 proberesponse 0   
stage 1 of 2 probing frequency 2432/5 proberesponse 0   
stage 1 of 2 probing frequency 2437/6 proberesponse 0   
stage 1 of 2 probing frequency 2442/7 proberesponse 0   
stage 1 of 2 probing frequency 2447/8 proberesponse 0   
stage 1 of 2 probing frequency 2452/9 proberesponse 0   
stage 1 of 2 probing frequency 2457/10 proberesponse 0   
stage 1 of 2 probing frequency 2462/11 proberesponse 0   
stage 1 of 2 probing frequency 2467/12 proberesponse 0   
stage 1 of 2 probing frequency 2472/13 proberesponse 0   
stage 1 of 2 probing frequency 2484/14 proberesponse 0   
stage 1 of 2 probing frequency 5180/36 proberesponse 0   
stage 1 of 2 probing frequency 5190/38 proberesponse 0   
stage 1 of 2 probing frequency 5200/40 proberesponse 0   
stage 1 of 2 probing frequency 5210/42 proberesponse 0   
stage 1 of 2 probing frequency 5220/44 proberesponse 0   
stage 1 of 2 probing frequency 5230/46 proberesponse 0   
stage 1 of 2 probing frequency 5240/48 proberesponse 0   
stage 1 of 2 probing frequency 5250/50 proberesponse 0   
stage 1 of 2 probing frequency 5260/52 proberesponse 0   
stage 1 of 2 probing frequency 5270/54 proberesponse 0   
stage 1 of 2 probing frequency 5280/56 proberesponse 0   
stage 1 of 2 probing frequency 5290/58 proberesponse 0   
stage 1 of 2 probing frequency 5300/60 proberesponse 0   
stage 1 of 2 probing frequency 5310/62 proberesponse 0   
stage 1 of 2 probing frequency 5320/64 proberesponse 0   
stage 1 of 2 probing frequency 5500/100 proberesponse 0   
stage 1 of 2 probing frequency 5510/102 proberesponse 0   
stage 1 of 2 probing frequency 5520/104 proberesponse 0   
stage 1 of 2 probing frequency 5530/106 proberesponse 0   
stage 1 of 2 probing frequency 5540/108 proberesponse 0   
stage 1 of 2 probing frequency 5550/110 proberesponse 0   
stage 1 of 2 probing frequency 5560/112 proberesponse 0   
stage 1 of 2 probing frequency 5570/114 proberesponse 0   
stage 1 of 2 probing frequency 5580/116 proberesponse 0   
stage 1 of 2 probing frequency 5590/118 proberesponse 0   
stage 1 of 2 probing frequency 5600/120 proberesponse 0   
stage 1 of 2 probing frequency 5610/122 proberesponse 0   
stage 1 of 2 probing frequency 5620/124 proberesponse 0   
stage 1 of 2 probing frequency 5630/126 proberesponse 0   
stage 1 of 2 probing frequency 5640/128 proberesponse 0   
stage 1 of 2 probing frequency 5650/130 proberesponse 0   
stage 1 of 2 probing frequency 5660/132 proberesponse 0   
stage 1 of 2 probing frequency 5670/134 proberesponse 0   
stage 1 of 2 probing frequency 5680/136 proberesponse 0   
stage 1 of 2 probing frequency 5690/138 proberesponse 0   
stage 1 of 2 probing frequency 5700/140 proberesponse 0   
stage 1 of 2 probing frequency 5745/149 proberesponse 0   
stage 1 of 2 probing frequency 5755/151 proberesponse 0   
stage 1 of 2 probing frequency 5765/153 proberesponse 0   
stage 1 of 2 probing frequency 5775/155 proberesponse 0   
stage 1 of 2 probing frequency 5785/157 proberesponse 0   
stage 1 of 2 probing frequency 5795/159 proberesponse 0   
stage 1 of 2 probing frequency 5805/161 proberesponse 0   
stage 1 of 2 probing frequency 5825/165 proberesponse 0   
stage 2 of 2 probing frequency 2412/1 proberesponse 0   
stage 2 of 2 probing frequency 2417/2 proberesponse 0   
stage 2 of 2 probing frequency 2422/3 proberesponse 0   
stage 2 of 2 probing frequency 2427/4 proberesponse 0   
stage 2 of 2 probing frequency 2432/5 proberesponse 0   
stage 2 of 2 probing frequency 2437/6 proberesponse 0   
stage 2 of 2 probing frequency 2442/7 proberesponse 0   
stage 2 of 2 probing frequency 2447/8 proberesponse 0   
stage 2 of 2 probing frequency 2452/9 proberesponse 0   
stage 2 of 2 probing frequency 2457/10 proberesponse 0   
stage 2 of 2 probing frequency 2462/11 proberesponse 0   
stage 2 of 2 probing frequency 2467/12 proberesponse 0   
stage 2 of 2 probing frequency 2472/13 proberesponse 0   
stage 2 of 2 probing frequency 2484/14 proberesponse 0   
stage 2 of 2 probing frequency 5180/36 proberesponse 0   
stage 2 of 2 probing frequency 5190/38 proberesponse 0   
stage 2 of 2 probing frequency 5200/40 proberesponse 0   
stage 2 of 2 probing frequency 5210/42 proberesponse 0   
stage 2 of 2 probing frequency 5220/44 proberesponse 0   
stage 2 of 2 probing frequency 5230/46 proberesponse 0   
stage 2 of 2 probing frequency 5240/48 proberesponse 0   
stage 2 of 2 probing frequency 5250/50 proberesponse 0   
stage 2 of 2 probing frequency 5260/52 proberesponse 0   
stage 2 of 2 probing frequency 5270/54 proberesponse 0   
stage 2 of 2 probing frequency 5280/56 proberesponse 0   
stage 2 of 2 probing frequency 5290/58 proberesponse 0   
stage 2 of 2 probing frequency 5300/60 proberesponse 0   
stage 2 of 2 probing frequency 5310/62 proberesponse 0   
stage 2 of 2 probing frequency 5320/64 proberesponse 0   
stage 2 of 2 probing frequency 5500/100 proberesponse 0   
stage 2 of 2 probing frequency 5510/102 proberesponse 0   
stage 2 of 2 probing frequency 5520/104 proberesponse 0   
stage 2 of 2 probing frequency 5530/106 proberesponse 0   
stage 2 of 2 probing frequency 5540/108 proberesponse 0   
stage 2 of 2 probing frequency 5550/110 proberesponse 0   
stage 2 of 2 probing frequency 5560/112 proberesponse 0   
stage 2 of 2 probing frequency 5570/114 proberesponse 0   
stage 2 of 2 probing frequency 5580/116 proberesponse 0   
stage 2 of 2 probing frequency 5590/118 proberesponse 0   
stage 2 of 2 probing frequency 5600/120 proberesponse 0   
stage 2 of 2 probing frequency 5610/122 proberesponse 0   
stage 2 of 2 probing frequency 5620/124 proberesponse 0   
stage 2 of 2 probing frequency 5630/126 proberesponse 0   
stage 2 of 2 probing frequency 5640/128 proberesponse 0   
stage 2 of 2 probing frequency 5650/130 proberesponse 0   
stage 2 of 2 probing frequency 5660/132 proberesponse 0   
stage 2 of 2 probing frequency 5670/134 proberesponse 0   
stage 2 of 2 probing frequency 5680/136 proberesponse 0   
stage 2 of 2 probing frequency 5690/138 proberesponse 0   
stage 2 of 2 probing frequency 5700/140 proberesponse 0   
stage 2 of 2 probing frequency 5745/149 proberesponse 0   
stage 2 of 2 probing frequency 5755/151 proberesponse 0   
stage 2 of 2 probing frequency 5765/153 proberesponse 0   
stage 2 of 2 probing frequency 5775/155 proberesponse 0   
stage 2 of 2 probing frequency 5785/157 proberesponse 0   
stage 2 of 2 probing frequency 5795/159 proberesponse 0   
stage 2 of 2 probing frequency 5805/161 proberesponse 0   
stage 2 of 2 probing frequency 5825/165 proberesponse 0   [?25h
warning: no PROBERESPONSE received - packet injection is probably not working!

```
</details>

I am running hcxdumptool with parameters:
`sudo hcxdumptool -i wlan1 -o OUT.pcapng -s 1 --enable_status=15`

And for a long time nothing happens:

![24-01-2024 07_46_27](https://github.com/ZerBea/hcxdumptool/assets/38177890/c1bcf47a-fcbd-47c3-9fde-9fdb4e418c68)

**Comment by ZerBea** [comment] 2024-01-24 09:45
Your problems in detail:
1) your hcxdumptool version 6.2..6 is outdated -> please update to latest release or latest git head
2) hcxdumptool does not have exclusive access to your device -> stop all services that have access to the device, e.g. NetworkManager and wpa-supplicant
3) iw config and ifconfig are deprecated and have been replaced by iw and ip

Closed this report, because it is related to your environment and not a bug.
If you have some further going questions, discussions is the right place for them.

**Closed by ZerBea** 2024-01-24 09:45 UTC
