### ISSUE TITLE
nexmon support

### ISSUE THREAD

**Issue by JuniorJPDJ** [ZerBea/hcxdumptool#44] opened 2019-02-18 04:29 UTC
Why can't I use nexmon patched firmware to dump?

nexmon: https://github.com/seemoo-lab/nexmon

```
 ⚡ root@samsung-jflte  ~  ip link set wlan0 down ; ip link set wlan0 up ; ./nexutil -m2 -d
 ⚡ root@samsung-jflte  ~  export LD_PRELOAD="./libfakeioctl.so"                                         
 ⚡ root@samsung-jflte  ~  strace -o strace.log ./hcxdumptool -i wlan0 -o hcx_fun          
initialization...
__nex_driver_io: error
failed to set monitor mode: No such device
failed to init socket
__nex_driver_io: error
 ✘ ⚡ root@samsung-jflte  ~  cat strace.log 
execve("./hcxdumptool", ["./hcxdumptool", "-i", "wlan0", "-o", "hcx_fun"], 0xbe849cd8 /* 25 vars */) = 0
set_tls(0xb6f78588)                     = 0
set_tid_address(0xb6f7852c)             = 4992
open("./libfakeioctl.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=13336, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\234\7\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 77824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6ee3000
mmap2(0xb6ef4000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1000) = 0xb6ef4000
close(3)                                = 0
mprotect(0xb6ef4000, 4096, PROT_READ)   = 0
mprotect(0xb6f9b000, 4096, PROT_READ)   = 0
getuid32()                              = 0
ioctl(1, TIOCGWINSZ, {ws_row=62, ws_col=271, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="initialization...", iov_len=17}, {iov_base="\n", iov_len=1}], 2) = 18
pipe2([3, 4], O_CLOEXEC)                = 0
pipe2([5, 6], O_CLOEXEC)                = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0xbefd2af0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 4993
close(6)                                = 0
read(5, "", 4)                          = 0
close(5)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
fcntl64(3, F_SETFD, 0)                  = 0
close(4)                                = 0
read(3, "", 1024)                       = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4993, si_uid=0, si_status=0, si_utime=0, si_stime=4} ---
close(3)                                = 0
wait4(4993, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 4993
pipe2([3, 4], O_CLOEXEC)                = 0
pipe2([5, 6], O_CLOEXEC)                = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0xbefd2af0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 4994
close(6)                                = 0
read(5, "", 4)                          = 0
close(5)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
fcntl64(3, F_SETFD, 0)                  = 0
close(4)                                = 0
read(3, "", 1024)                       = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4994, si_uid=0, si_status=0, si_utime=0, si_stime=3} ---
close(3)                                = 0
wait4(4994, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 4994
socket(AF_PACKET, SOCK_RAW, 768)        = 3
ioctl(3, SIOCGIFFLAGS, {ifr_name="wlan0", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
ioctl(3, SIOCGIWMODE, 0xb6fa01ec)       = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCDEVPRIVATE, 0xb6f76110)    = 0
close(4)                                = 0
ioctl(3, SIOCSIFFLAGS, {ifr_name="wlan0", ifr_flags=0}) = 0
ioctl(3, SIOCSIWMODE, 0xb6fa0e04)       = -1 EOPNOTSUPP (Not supported)
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCDEVPRIVATE, 0xb6f76110)    = -1 ENODEV (No such device)
writev(1, [{iov_base="__nex_driver_io", iov_len=15}, {iov_base=": error\n", iov_len=8}], 2) = 23
close(4)                                = 0
writev(2, [{iov_base="", iov_len=0}, {iov_base="failed to set monitor mode", iov_len=26}], 2) = 26
writev(2, [{iov_base="", iov_len=0}, {iov_base=":", iov_len=1}], 2) = 1
writev(2, [{iov_base="", iov_len=0}, {iov_base=" ", iov_len=1}], 2) = 1
writev(2, [{iov_base="", iov_len=0}, {iov_base="No such device", iov_len=14}], 2) = 14
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2) = 1
writev(2, [{iov_base="", iov_len=0}, {iov_base="failed to init socket\n", iov_len=22}], 2) = 22
ioctl(3, SIOCSIFFLAGS, {ifr_name="wlan0", ifr_flags=0}) = 0
ioctl(3, SIOCSIWMODE, 0xb6fa01ec)       = -1 EOPNOTSUPP (Not supported)
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCDEVPRIVATE, 0xb6f76110)    = -1 ENODEV (No such device)
writev(1, [{iov_base="__nex_driver_io", iov_len=15}, {iov_base=": error\n", iov_len=8}], 2) = 23
close(4)                                = 0
ioctl(3, SIOCSIFFLAGS, {ifr_name="wlan0", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by ZerBea** [comment] 2019-02-18 17:27
Did you activate nexmon monitor?
https://github.com/seemoo-lab/nexmon
Using the Monitor Mode patch
    Thanks to the prior work of Mame82, you can setup a new monitor mode interface by executing: iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor
    To activate monitor mode in the firmware, simply set the interface up: ifconfig mon0 up.
    At this point, monitor mode is active. There is no need to call airmon-ng.
    The interface already set the Radiotap header, therefore, tools like tcpdump or airodump-ng can be used out of the box: tcpdump -i mon0

**Comment by JuniorJPDJ** [comment] 2019-02-18 22:49
This modified driver for Raspberry Pi is not working on phones as far as I know, I'm using libfakeioctl in LD_PRELOAD to simulate monitor mode on non-monitor-mode capable interface.
This way I can make it work with bettercap.

**Comment by ZerBea** [comment] 2019-02-19 07:07
You got 2 error messages from hcxdumptool:
failed to set monitor mode: No such device -> hcxdumptool can't find the interface
failed to init socket -> hcxdumptool can't create a raw socket to receive and transmit raw packets
Error 2 is related to error 1. If we have no interface, we can't send or receive packets .

So let's see if monitor mode is working and iw is able to detect the device. Please set the interface to monitor mode: 
iw dev <interface> set type monitor
and comment the result:
sudo iw dev <interface> info

If everything is ok, we expect no error message running this command:
iw dev wlp3s0f0u1 set type monitor
and we expect an output like this for the second command:
Interface wlp3s0f0u1
	ifindex 3
	wdev 0x1
	addr c8:3a:35:e0:f4:52
	type monitor
	wiphy 0
	txpower 20.00 dBm

**Comment by JuniorJPDJ** [comment] 2019-02-23 07:45
nexmon doesn't allow me to set interface to monitor mode, it's emulating it by preloaded library
It's not modifying driver to allow monitor mode, it's modifying just wifi firmware and emulating monitor for apps using preloaded library
iw doesn't show the interface as monitor mode even with preloading library

**Comment by ZerBea** [comment] 2019-02-23 07:56
In that case hcxdumptool will not work for you, because the emulator doesn't allow this:
"nexmon doesn't allow me to set interface to monitor mode"

$ hcxdumptool --help
         do not run hcxdumptool on logical interfaces (monx, wlanxmon)
         do not use hcxdumptool in combination with other 3rd party tools, which take access to the interface

Closed this issue, because it is related to the emulator.

**Closed by ZerBea** 2019-02-23 07:56 UTC

**Comment by ZerBea** [comment] 2019-02-23 08:23
Please read also all comments here:
https://github.com/ZerBea/hcxdumptool/issues/42
to understand  that the driver (in your case the emulator) must support full and hardware near monitor mode, included raw packet injection.
Only if the driver supports this, hcxdumptool will work.

**Comment by JuniorJPDJ** [comment] 2019-02-23 21:47
It supports monitor mode and packet injection, but doesn't report it.
Ioctls are overwritten on preloaded library.
To set firmware to monitor mode you need to use custom software, not linux API.
I commented section that sets interface to monitor mode and it ALMOST works.
It captures packets with NEXMON header, which should be handled by preloaded library and passed to hcxdumptool as normal RADIOTAP.

**Comment by ZerBea** [comment] 2019-02-24 08:50
The issue is within the preloaded library:
__nex_driver_io: error

and hcxdudmptool reports correctly:
failed to set monitor mode: No such device
failed to init socket

ioctl(3, SIOCSIWMODE, 0xb6fa0e04)       = -1 EOPNOTSUPP (Not supported)
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCDEVPRIVATE, 0xb6f76110)    = -1 ENODEV (No such device)
writev(1, [{iov_base="__nex_driver_io", iov_len=15}, {iov_base=": error\n", iov_len=8}], 2) = 23
...
ioctl(3, SIOCSIWMODE, 0xb6fa01ec)       = -1 EOPNOTSUPP (Not supported)
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
ioctl(4, SIOCDEVPRIVATE, 0xb6f76110)    = -1 ENODEV (No such device)
writev(1, [{iov_base="__nex_driver_io", iov_len=15}, {iov_base=": error\n", iov_len=8}], 2) = 23


hcxdumptool needs the ioctls, otherwise it will not work:

start capturing (stop with ctrl+c)
INTERFACE:...............: wlp3s0f0u1
ERRORMAX.................: 100 errors
FILTERLIST...............: 0 entries
MAC CLIENT...............: b0ece1f25217
MAC ACCESS POINT.........: 0084edce9fef (incremented on every new client)
EAPOL TIMEOUT............: 150000
REPLAYCOUNT..............: 64046
ANONCE...................: 60f6f16c3028e0d9ed6450d82b176c7be213d7a4162e64f486638b4b8bb474ec

INFO: cha=6, rx=0, rx(dropped)=0, tx=30, powned=0, err=0
