### ISSUE TITLE
hcxdumptool stops if TERM is not set

### ISSUE THREAD

**Issue by RaduNico** [ZerBea/hcxdumptool#327] opened 2023-06-14 04:01 UTC
I've been trying to run hcxdumptool as part of a systemd service on a raspberry pi and saving the output to a file. Due to me trying to run it this way, the TERM environmental variable was not set, resulting in the error "TERM environment variable not set." being printed out like this:
```
[...]
   LAST   E 2 MAC-AP-ROGUE   MAC-CLIENT   ESSID (last seen on top)
-----------------------------------------------------------------------------------------
<client>
TERM environment variable not set.
  CHA    LAST   R 1 3 P S    MAC-AP    ESSID (last seen on top)   SCAN-FREQUENCY:   2462
-----------------------------------------------------------------------------------------
<APs>                                                        




   LAST   E 2 MAC-AP-ROGUE   MAC-CLIENT   ESSID (last seen on top)
-----------------------------------------------------------------------------------------
<client>
TERM environment variable not set.
  CHA    LAST   R 1 3 P S    MAC-AP    ESSID (last seen on top)   SCAN-FREQUENCY:   2412
-----------------------------------------------------------------------------------------
<APs>



 
   LAST   E 2 MAC-AP-ROGUE   MAC-CLIENT   ESSID (last seen on top)
-----------------------------------------------------------------------------------------
<client>
[...]
101 errors during runtime

exit on error

bye-bye
```

When the threshold number of errors was being reached the program would stop working. this is caused by line 510 of hcxdumptool.c `if(system("clear") != 0) errorcount++;`, esentially the clear command is erroring out. I understand this might be the expected behavior and if that is the case this finding can be marked as solved.

Simply setting the TERM environment variable is a good workaround for anyone encountering this specific issue.

Edit: Since running hcxdumptool like this is esentially running it in headless mode, an even better workaround is disabling printing entirely by modifying the Makefile from:

`DEFS		+= -DSTATUSOUT -DNMEAOUT`
to
`DEFS		+= -DNMEAOUT`

This was pointed out in another issue and fixes the problem since printing is not really necessary or all that useful when running as a service. It might be worth mentioning the possibility to disable printing entirely in [README.md](https://github.com/ZerBea/hcxdumptool/blob/master/README.md) in order to more efficiently run in headless mode.

**Comment by ZerBea** [comment] 2023-06-14 06:33
Usually hcxdumptool is not designed to run as a service, but as you mentioned, you can compile a "headless mode" where printing is disabled. 
The behavior is wanted because most of the users want a status display. If the screen can't be cleared, errorcaount increase.
On headless operation, it is mandatory to remove STATUSOUT (this will save a lot of CPU cycles).
I'll add this to README.md.

The thresh old of 100 errors make sense. When so many errors have occurred there is a serious problem with the OS (e.g. driver doesn't support monitor mode), hardware (device doesn't support packet injection), procedure (e.g. NetworkManager still running) or configuration (e.g. environment variable not set). 

Closed this report, because it is not a bug.

**Closed by ZerBea** 2023-06-14 06:33 UTC
